## You should change each of the following fields
## to customize your blog

title: "Blogging a Data Science Class"
description: "Following along with some stats along the way" 
author: Dylan Bay
author_description: "I'm a student at BYU in the Statistics department, with an emphasis in Data Science and graduating in April 2025. I love from hearing from people, so feel free to drop me an email!" 

url: https://dylanbay11.github.io ## change this to https://yourusername.github.io
baseurl: /blog_home ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  dylanbay11 ## required
    twitter: 
    facebook: 
    email:  dylanbay11@gmail.com
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




